/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code;

import java.awt.Image;
import java.awt.geom.RoundRectangle2D;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kunal
 */
public class Main_Frame extends javax.swing.JFrame {
    int choise,count=1,score,rmd; 
     boolean check =false;
    int check_Result()
    {
      int temp;
        if(rmd==choise)
            temp = 1;
        else if(rmd<choise)
            temp = 2;
        else 
            temp = 3;   
        
    return  temp;
    }
    void getvalue()
    {
         if(value_textfield.equals(""))
                JOptionPane.showMessageDialog(null,"You Have To Choose Any number");
            else          
                choise=Integer.parseInt(value_textfield.getText());             
    }
    void  clearAll()
    {
        value_textfield.setText(null);
        result_labbel.setText(null);
        guess_textfield.setText("-");      
        
    }
    int highestScore(int temp)
    {
        if(temp>score){            
            return score;           
        }
        else
        {
            score=temp;
            return score;
        }                 
    }
    void imgesResize(){
       ImageIcon li = new ImageIcon(getClass().getResource("/img/Quation Hold man.png"));
       Image image = (li).getImage().getScaledInstance(img_labbel.getWidth(),img_labbel.getHeight(),Image.SCALE_SMOOTH);    
       li = new ImageIcon(image);      
       img_labbel.setIcon(li);
    }
    void random_number()
    {        
        Random r = new Random();
        rmd = r.nextInt(100);        
    }
    public Main_Frame() {
       setUndecorated(true);
       initComponents(); 
       setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),50,80));
       imgesResize();
       random_number();
       clearAll();
       guess_textfield.setEditable(false);
       score_textfield.setEditable(false);           
       value_textfield.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img_labbel = new javax.swing.JLabel();
        guess_textfield = new javax.swing.JTextField();
        score_textfield = new javax.swing.JTextField();
        guess_labbel = new javax.swing.JLabel();
        best_score_labbel = new javax.swing.JLabel();
        title_labbel = new javax.swing.JLabel();
        result_labbel = new javax.swing.JLabel();
        value_textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        play_again_button = new javax.swing.JButton();
        give_up_buttpn = new javax.swing.JButton();
        guess_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guess The Number");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        guess_textfield.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        guess_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guess_textfield.setText("-");
        guess_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guess_textfieldActionPerformed(evt);
            }
        });

        score_textfield.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        score_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        score_textfield.setText("-");
        score_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                score_textfieldActionPerformed(evt);
            }
        });

        guess_labbel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        guess_labbel.setText("Guesses :-");

        best_score_labbel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        best_score_labbel.setText("Best Score :-");

        title_labbel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title_labbel.setForeground(new java.awt.Color(255, 102, 102));
        title_labbel.setText("Guess My Number Game");

        result_labbel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        result_labbel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        value_textfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        value_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        value_textfield.setText("-");
        value_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                value_textfieldFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Enter The Number b/w 1-100");

        play_again_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        play_again_button.setText("Play Again");
        play_again_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play_again_buttonActionPerformed(evt);
            }
        });

        give_up_buttpn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        give_up_buttpn.setText("Give Up");
        give_up_buttpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                give_up_buttpnActionPerformed(evt);
            }
        });

        guess_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        guess_button.setText("Guess");
        guess_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guess_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Designed By aurthor ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(best_score_labbel)
                .addGap(18, 18, 18)
                .addComponent(score_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(guess_labbel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guess_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(img_labbel, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 103, Short.MAX_VALUE))
                            .addComponent(title_labbel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(give_up_buttpn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(play_again_button, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(value_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(guess_button, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(result_labbel, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guess_labbel)
                    .addComponent(score_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(best_score_labbel)
                    .addComponent(guess_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(img_labbel, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(title_labbel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(value_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(result_labbel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(play_again_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(give_up_buttpn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(guess_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guess_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guess_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guess_textfieldActionPerformed

    private void score_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_score_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_score_textfieldActionPerformed

    private void give_up_buttpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_give_up_buttpnActionPerformed
        
        int choise = JOptionPane.showConfirmDialog(null,"Are You Want To Quit..!","Exit",JOptionPane.OK_CANCEL_OPTION );
        if(choise==JOptionPane.OK_OPTION)
         dispose();          
    }//GEN-LAST:event_give_up_buttpnActionPerformed

    private void guess_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guess_buttonActionPerformed
        value_textfield.requestFocus();
        try {
            getvalue();
            value_textfield.setText(null);             
            guess_textfield.setText(""+count);   
           switch (check_Result()) {
                case 1:
                    result_labbel.setText("Number Found...\n You Won...");
                    if(score==0)
                        score=count;
                    check=true;
                    break;
                case 2:
                    result_labbel.setText("You Should choose Quite small Number...");
                    count++;
                    check=false;
                    break;
                default:
                    result_labbel.setText("You Should choose Quite larg Number...");
                    count++;  
                    check=false;
                    break;
            }              
        } 
     catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Please Use Number...");
        }       
   
    }//GEN-LAST:event_guess_buttonActionPerformed

    private void value_textfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_value_textfieldFocusLost
     
    }//GEN-LAST:event_value_textfieldFocusLost

    private void play_again_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play_again_buttonActionPerformed
        if(check)
         score_textfield.setText(""+highestScore(count));
        value_textfield.requestFocus();
        clearAll();
        random_number();
        count=1;
    }//GEN-LAST:event_play_again_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel best_score_labbel;
    private javax.swing.JButton give_up_buttpn;
    private javax.swing.JButton guess_button;
    private javax.swing.JLabel guess_labbel;
    private javax.swing.JTextField guess_textfield;
    private javax.swing.JLabel img_labbel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton play_again_button;
    private javax.swing.JLabel result_labbel;
    private javax.swing.JTextField score_textfield;
    private javax.swing.JLabel title_labbel;
    private javax.swing.JTextField value_textfield;
    // End of variables declaration//GEN-END:variables
}
